FROM nginx:alpine


RUN apk add \
 curl \
 gettext \
 bash

EXPOSE 80
COPY start.sh /
COPY index.html.tmpl /
RUN chmod +x /start.sh
ENV TITLE=Default-Title
ENV BGC=grey
ENV BODY="Please use TITLE/BGC/BODY env vars"
ENV WWW_DIR=/usr/share/nginx/html
CMD [ "/start.sh" ]