services:
  proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  dinner:
    image: lalyos/lunch:v8
    environment:
      - TITLE=${TITLE:?required}
      - BGC=${BGC:?required}
      - BODY=${BODY:?required}
      - VIRTUAL_HOST=dinner.lvh.me
      - VIRTUAL_PORT=80
    ports:
      - 80
  coffee:
    image: lalyos/lunch:v8
    environment:
      - TITLE=Kaveszunet
      - BGC=tan
      - VIRTUAL_HOST=coffe.lvh.me
      - VIRTUAL_PORT=80
    ports:
      - 80
  mydb:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - vipdb:/var/lib/postgresql/data
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080
volumes:
   vipdb: